version: '3.8'

services:
    frontend:
        container_name: next
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - /app/node_modules
        networks:
            - next-fastapi-backend_dev-network
networks:
    next-fastapi-backend_dev-network:
        external: true
